server:
  port: 8080
# Spring의 기본 프로필 설정
spring:
  profiles:
    active: local
# OpenAI API 관련 공통 설정값
openai:
  api:
    url: https://api.openai.com/v1/chat/completions
    model: gpt-3.5-turbo